
version: 2

sources:
  - name: ga360
    schema: google_analytics_sample
    database: bigquery-public-data
    tables:
      - name: ga_sessions_20170701
        freshness: # GA360 transfers are 24 hours apart. This sample data is stale, so it of course won't actually be fresh.
          #warn_after: {count: 24, period: hour}
          #error_after: {count: 30, period: hour}

models:
    - name: base_hits
      description: '{{ doc("base_hits") }}'
    - name: stg_hits
      description: '{{ doc("stg_hits") }}'
      columns:
          - name: sessionId
            description: 'Primary key of the table, created as a composition to rectify downsides of the out-of-the-box sessionid key. Using this key keeps-alive a session overnight among other minor annoyances with the original sessionid.'
            tests:
              - unique
              - not_null
    - name: added_conversions
      description: 'Used event category, event label, and event action to map out the custom conversions (Goals) achieved by a user in a session'
    - name: added_landing_pages
      description: 'Takes the first page visited on an entrance and records it as a landing page for analysis'
    - name: aggregated_hits_to_sessions
      description: 'Reaggragate the hit level data back to session level granularity'
      
      



