version: 2

sources:
  - name: ga360
    schema: google_analytics_sample
    database: bigquery-public-data
    tables:
      - name: "ga_sessions_2017*"
        identifier: sessions
        freshness: # GA360 transfers are 24 hours apart. This sample data is stale, so it of course won't actually be fresh.
          #warn_after: {count: 24, period: hour}
          #error_after: {count: 30, period: hour}

# Compliles to `bigquery-public-data.google_analytics_sample.ga_sessions_20170101`